name: ci
on:
  pull_request:
  release:
    types: [published]
  push:
    branches:
      - main
      - develop

env:
  CLANG_TIDY_VERSION: "19.1.0"
  VERBOSE: 1

jobs:
  Build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - llvm-19.1.0
        generator:
          - "Ninja Multi-Config"
        build_type:
          - Release
          - Debug

    steps:
      - uses: actions/checkout@v3

      - name: Install newer libstdc++ from GCC 11
        run: |
          sudo apt update
          sudo apt install -y g++-11
          echo "CXXFLAGS=-stdlib=libstdc++" >> $GITHUB_ENV

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
          ninja: true
          ccache: true
          clangtidy: ${{ env.CLANG_TIDY_VERSION }}

      - name: Check Compiler Versions
        run: |
          clang++ --version
          g++ --version

      - name: Configure CMake
        run: |
          cmake -S . -B ./build -G "${{ matrix.generator }}" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: |
          cmake --build ./build --config ${{ matrix.build_type }}

      - name: Run Tests
        run: |
          for dir in build/libs/core build/libs/cortex build/libs/exec build/libs/asymtx; do
            echo "Running tests in $dir..."
            if [ -d "$dir" ]; then
              ctest -C ${{ matrix.build_type }} --test-dir $dir --verbose || exit 1
            else
              echo "Warning: $dir not found, skipping..."
            fi
          done
