name: ci
on:
  pull_request:
  release:
    types: [published]
  push:
    branches:
      - main
      - develop

env:
  CLANG_TIDY_VERSION: "19.1.0"
  VERBOSE: 1

jobs:
  Build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - llvm-19.1.0
        generator:
          - "Ninja Multi-Config"
        build_type:
          - Release
          - Debug
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
          ninja: true
          ccache: true
          clangtidy: ${{ env.CLANG_TIDY_VERSION }}

      - name: Configure CMake
        run: |
          cmake -S . -B ./build -G "${{matrix.generator}}" -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

      - name: Build
        run: |
          cmake --build ./build --config ${{matrix.build_type}}
